spring:
  # 순환 참조 허용 (개발용)
  main:
    allow-circular-references: true
    
  # 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2 Console 설정 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  
  # SQL 초기화
  sql:
    init:
      mode: always

# JWT 설정
jwt:
  secret: mySecretKey1234567890123456789012345678901234567890
  expiration: 86400000 # 24시간

# 로깅 설정
logging:
  level:
    com.shop: DEBUG
    org.springframework.security: DEBUG 